export enum CreatureTypeTraits {
    Aberration = 'Aberration',
    Animal = 'Animal',
    Astral = 'Astral',
    Beast = 'Beast',
    Celestial = 'Celestial',
    Construct = 'Construct',
    Dragon = 'Dragon',
    Dream = 'Dream',
    Elemental = 'Elemental',
    Ethereal = 'Ethereal',
    Fey = 'Fey',
    Fiend = 'Fiend',
    Fungus = 'Fungus',
    Giant = 'Giant',
    Humanoid = 'Humanoid',
    Monitor = 'Monitor',
    Negative = 'Negative',
    Ooze = 'Ooze',
    Petitioner = 'Petitioner',
    Plant = 'Plant',
    Positive = 'Positive',
    Spirit = 'Spirit',
    Time = 'Time',
    Undead = 'Undead',

}
