export enum PlanarTraits {
    Air = 'Air',
    Earth = 'Earth',
    Erratic = 'Erratic',
    Finite = 'Finite',
    Fire = 'Fire',
    Flowing = 'Flowing',
    HighGravity = 'High Gravity',
    Immeasurable = 'Immeasurable',
    LowGravity = 'Low Gravity',
    Metamorphic = 'Metamorphic',
    Microgravity = 'Microgravity',
    Negative = 'Negative',
    Positive = 'Positive',
    Sentient = 'Sentient',
    Shadow = 'Shadow',
    Static = 'Static',
    StrangeGravity = 'Strange Gravity',
    SubjectiveGravity = 'Subjective Gravity',
    Timeless = 'Timeless',
    Unbounded = 'Unbounded',
    Water = 'Water',
}
